//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor_Table
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Company { get; set; }
        public string Visiting { get; set; }
        public string Id_Type { get; set; }
        public string Id_No { get; set; }
        public string Vehicle_No { get; set; }
        public string Contact_No { get; set; }
        public string Purpose_Of_Visit { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Entry_Time { get; set; }
        public Nullable<System.DateTime> Exit_Time { get; set; }
    }
}
